### Autograd

In [2]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [3]:
a = [1, 2, 3, 4]
b = torch.tensor(a)
print(b)
print(torch.square(b))

tensor([1, 2, 3, 4])
tensor([ 1,  4,  9, 16])


In [4]:
prediction = model(data) # forward pass
print(prediction.shape)
print(torch.max(prediction))
print(torch.min(prediction))

torch.Size([1, 1000])
tensor(2.5172, grad_fn=<MaxBackward1>)
tensor(-2.5340, grad_fn=<MinBackward1>)


Test 1:

In [18]:
model = torchvision.models.resnet18(pretrained=True)


In [19]:
data1 = torch.rand(1, 3, 64, 64)
labels1 = torch.rand(1, 1000)
prediction1 = model(data1)

In [20]:
data2 = torch.rand(1, 3, 64, 64)
labels2 = torch.rand(1, 1000)
prediction2 = model(data2)

In [22]:
if not(torch.equal(prediction1, prediction2)):
    print('ok')

ok


In [23]:
print(prediction1)
print(prediction2)

tensor([[-4.5511e-01, -3.6743e-01, -5.8805e-01, -1.5422e+00, -7.5299e-01,
         -3.6111e-01, -5.4993e-01,  7.1054e-01,  4.8580e-01, -5.5755e-01,
         -7.2881e-01, -6.1895e-01, -6.2567e-02, -9.0490e-01, -8.4646e-01,
         -2.3917e-01, -8.8522e-01, -2.6288e-01, -5.2434e-01, -7.0390e-01,
         -1.1917e+00, -4.2785e-01, -9.9750e-01,  2.6589e-01, -8.2751e-01,
         -1.1664e+00, -8.2430e-01, -1.0600e+00, -1.0474e+00, -4.1731e-01,
         -5.7748e-01, -4.0502e-01, -1.3735e-01, -5.2076e-01, -3.1951e-01,
         -3.5655e-01,  8.0285e-01, -7.9180e-01, -3.5460e-01,  1.9700e-01,
         -5.8004e-01, -6.6157e-01, -9.8080e-01, -1.3922e-01, -5.6934e-01,
         -5.9627e-01, -6.5950e-01, -2.8263e-01, -1.1890e+00, -8.0020e-01,
         -4.6047e-01,  4.4985e-01, -3.9508e-01, -6.2967e-01, -5.0529e-02,
         -1.0204e+00, -1.1310e-01, -1.2844e+00, -4.0506e-01, -2.0167e-01,
          7.6586e-01,  2.7333e-01,  4.9640e-02,  2.9168e-01, -5.8019e-01,
         -2.8523e-01, -1.7089e-01, -2.

Test 2:

In [24]:
data1 = torch.rand(1, 3, 64, 64)
labels1 = torch.rand(1, 1000)
prediction1 = model(data1)

In [25]:
data2 = torch.ones(1, 3, 64, 64)
labels2 = torch.ones(1, 1000)
prediction2 = model(data2)

In [26]:
if not(torch.equal(prediction1, prediction2)):
    print('ok')

ok


Test 3:

In [27]:
data1 = torch.ones(1, 3, 64, 64)
labels1 = torch.ones(1, 1000)
prediction1 = model(data1)

In [28]:
data2 = torch.ones(1, 3, 64, 64)
labels2 = torch.ones(1, 1000)
prediction2 = model(data2)

In [29]:
if (torch.equal(prediction1, prediction2)):
    print('ok')

ok


In [30]:
loss = (prediction - labels).sum()
print(loss)
loss.backward() # backward pass
print(type(loss))
print(loss.shape)

tensor(-481.3195, grad_fn=<SumBackward0>)
<class 'torch.Tensor'>
torch.Size([])


In [31]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [32]:
optim.step() #gradient descent

In [36]:
optim.step() #gradient descent